DataDog/pg_tracing

- Makefile
- doc/pg_tracing.md
- expected/parallel.out
- sql/parallel.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_parallel.c
On parallel query, save the tracecontext in a shared memory. Parallel worker will be able to pull the tracecontext from it and generate spans on their own.
We want to trace workers spawned by parallel queries.
> Add tracing of parallel queries

- Makefile
- expected/planstate_projectset.out
- sql/planstate_projectset.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_planstate.c
Use parent planstate as span end for top level spans.
Top spans end are currently ended at the end of the parent's ExecutorRun while nodes will rely on query instrumentation. This can lead to a situation where a node with nested queries like ProjectSet is shorter than its children.
We already use traced_planstate to correctly assign parent for a nested top span. We will keep track of the traced_planstate in the span and use it to when ending the top span.
> Fix top span end

- Makefile
- expected/cursor.out
- sql/cursor.sql
- src/pg_tracing.c
When fetching an existing cursors, the portal already exists and the query directly starts from ExecutorRun without going through planner, post_parse or ExecutorStart. Since top spans were only initialised within those 3 hooks, cursor fetch wouldn't have a matching top span.
This commit fixes the issue by creating the top span in ExecutorRun if it doesn't exist.
Fixes #10
> Create top span in ExecutorRun hook if needed

- Makefile
- expected/cursor.out
- expected/select.out
- expected/transaction.out
- sql/cursor.sql
- sql/transaction.sql
- src/pg_tracing.c
If the start of a transaction has a trace_context, we want to reuse it for the whole transaction. Replace latest_trace_id by tx_start_traceparent which will only be set at the start of a new transaction and update it with both randomly generated trace_id and extracted_trace_id from SQLComments.
If a statement has its own tracecontext, we give it priority.
This fixes the issue #13 where latest_trace_id was not updated when trace_id was provided by SQLComment, leading to creating spans with a 0 trace_id.
> Replace latest_trace_id by tx_start_traceparent

- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_active_spans.c
- src/pg_tracing_parallel.c
- src/pg_tracing_span.c
Root span in the trace_context was used to deal with the extended protocol + transaction block issue: The parse of the next statement happens while the previous statement is ongoing since the portal is only dropped during the bind command.
We can replace it by a specific next_active_span to store span's information when we hit this case and restore it when needed.
We also remove max_nested_level: we can track whether pg_tracing memory context is allocated by checking pg_tracing_mem_ctx->isReset, making max_nested_level redundant.
> Remove root span and max_nested_level

- expected/extended.out
- expected/full_buffer.out
- expected/nested.out
- expected/planstate.out
- expected/select.out
- expected/setup.out
- expected/subxact.out
- expected/utility.out
- sql/full_buffer.sql
- sql/nested.sql
- sql/planstate.sql
- sql/select.sql
- sql/setup.sql
- sql/subxact.sql
- sql/utility.sql
- src/pg_tracing.c
We can't rely on parse or executor traceparent to be set when dealing with extended protocol. Switch to mostly rely on current_trace_spans to know whether trace needs to be pushed in the shared buffer.
Also fix query_id for commit span within process utility.
> Rework conditions for end of trace

- expected/cursor.out
- expected/extended.out
- expected/nested.out
- expected/planstate.out
- expected/planstate_bitmap.out
- expected/planstate_hash.out
- expected/planstate_projectset.out
- expected/planstate_union.out
- expected/sample.out
- expected/select.out
- expected/trigger_15.out
- expected/trigger_16.out
- expected/utility.out
- sql/utility.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_active_spans.c
Commit on read only transaction is mostly a no-op and create more noise with possible 0ms duration spans. We're mostly interested in commit span that are possibly doing works like writing wal, fsync or waiting for a synchronous replicas.
> Only create commit span on modifying transaction

- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_active_spans.c
- src/pg_tracing_planstate.c
Move planstate manipulation functions to pg_tracing_planstate
Make hook functions more consistent: Check and bail out early if statement is not sampled
Replaced end_latest_active_span by pop_active_span
> Renaming and refactoring

- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_query_process.c
- src/pg_tracing_sql_functions.c
Fix possible race condition where writes could happen between reading and acquiring the lock.
Also add missing free of the malloced qbuffer.
> Fix qbuffer race condition

- Dockerfile
- Makefile
- doc/pg_tracing.md
- expected/cleanup.out
- expected/json.out
- expected/utility.out
- pg_tracing--0.1.0.sql
- sql/cleanup.sql
- sql/json.sql
- sql/utility.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_json.c
- src/pg_tracing_otel.c
- src/pg_tracing_sql_functions.c
- t/001_basic.pl
- t/002_connect_timeout.pl
Create a background worker for  that will export send spans to a otel collector at regular interval.
Spans are consumed by the worker from the shared_spans buffer and sent as json using http1 with libcurl.
> Create background worker to send spans to an otel collector

- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_active_spans.c
- src/pg_tracing_json.c
- src/pg_tracing_otel.c
- src/pg_tracing_parallel.c
- src/pg_tracing_planstate.c
- src/pg_tracing_query_process.c
- src/pg_tracing_span.c
- src/pg_tracing_sql_functions.c
- src/version_compat.h
Introduce span_context structure to simplify passing all arguments (Query, PlannedStatement, query_text...) to span creation.
> Refactoring span context

- Makefile
- expected/guc.out
- sql/guc.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_query_process.c
Create a `pg_tracing.trace_context` guc parameter that allows to propagate tracecontext through GUC.
Example of usage:
```
SET pg_tracing.trace_context='dddbs=''postgres.db'',traceparent=''00-fffffffffffffffffffffffffffffff5-0000000000000005-01';
SELECT 2;
SET pg_tracing.trace_context TO default;
```
> Add possibility to set tracecontext guc value

- expected/cursor.out
- expected/extended.out
- expected/insert.out
- expected/nested.out
- expected/parallel.out
- expected/planstate.out
- expected/select.out
- expected/transaction.out
- expected/trigger.out
- expected/utility.out
- expected/wal.out
- sql/nested.sql
- sql/parallel.sql
- sql/trigger.sql
- sql/utility.sql
- src/pg_tracing.h
- src/pg_tracing_explain.c
- src/pg_tracing_json.c
- src/pg_tracing_otel.c
- src/pg_tracing_planstate.c
- src/pg_tracing_span.c
- src/pg_tracing_sql_functions.c
Group spans by span_type (Planner, Select Query, SeqScan...) by using scopeSpans from OTLP/json.
> Group spans by scope in json export

- Makefile
- expected/extended.out
- expected/guc.out
- expected/json.out
- expected/planstate.out
- expected/planstate_bitmap.out
- expected/planstate_projectset.out
- expected/planstate_subplans.out
- expected/planstate_union.out
- expected/sample.out
- expected/select.out
- expected/subxact.out
- expected/utility.out
- pg_tracing--0.1.0.sql
- sql/json.sql
- sql/utility.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_active_spans.c
- src/pg_tracing_explain.c
- src/pg_tracing_json.c
- src/pg_tracing_otel.c
- src/pg_tracing_planstate.c
- src/pg_tracing_query_process.c
- src/pg_tracing_span.c
- src/pg_tracing_sql_functions.c
- t/002_connect_timeout.pl
- Keep worker id in the span instead of keeping "Worker x" in the query text.
- Don't repeat span_type in the operation name. For names like "Index Scan on table", "index scan" can be generated from the span_type so only store "on table" in the query text
- Ourtput parameters as text[] insteand of a single string
> Optimise text stored in query text

- src/pg_tracing_planstate.c
During first node execution, we generate a span_id. However, we only use if for Result and ProjectSet node.
Always use span_id from traced_planstate to avoid redundant span_id generation.
Fixes #34
> Reuse span_id from traced_planstate

- expected/transaction.out
- sql/transaction.sql
- src/pg_tracing.c
- src/pg_tracing_otel.c
- src/version_compat.c
When a statement is sampled within a transaction, save trace_id to be reused but don't set the whole transaction to be sampled.
> Fix set of trace_id for tx_start_traceparent

- expected/cursor.out
- expected/extended.out
- expected/guc.out
- expected/setup.out
- expected/subxact.out
- expected/transaction.out
- sql/cursor.sql
- sql/guc.sql
- sql/setup.sql
- sql/transaction.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_span.c
When a transaction is started with an explicit begin, create a dedicated transaction span that will be used as a parent for the whole transaction and ends with commit/abort.
> Add transaction block span

- src/pg_tracing.h
- src/pg_tracing_json.c
- src/pg_tracing_otel.c
- src/pg_tracing_sql_functions.c
- t/002_connect_timeout.pl
To avoid locking spans with an exclusive lock while sending the json payload to the collector, we create a copy of both spans and spans_str and immediately release the lock.
From the copy, we marshal the json payload to be sent and attempt to send it. We keep this payload until send is successful.
> Work on a copy of spans before sending to otel collector

- expected/extended.out
- expected/parallel.out
- expected/transaction.out
- sql/parallel.sql
- sql/transaction.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_operation_hash.c
- src/pg_tracing_span.c
- src/pg_tracing_sql_functions.c
Query id can be set to 0 despite compute_query_id being set. Fallback to store the query string without using the hashmap in this case.
Also modify the creation of the tx_block spans: If we are in a middle of a tx_block and there's no existing tx_block span, create one.
> Handle 0 query id and tune tx_block spans

- Makefile
- doc/pg_tracing.md
- expected/parameters.out
- expected/parameters_16.out
- expected/select.out
- expected/setup.out
- sql/parameters.sql
- sql/parameters_16.sql
- sql/select.sql
- sql/setup.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_active_spans.c
- src/pg_tracing_query_process.c
- src/pg_tracing_span.c
- src/pg_tracing_sql_functions.c
`pg_tracing.max_parameter_size` GUC parameter was present but never used. Use it to apply possibly truncate string stored in the parameter buffer shared across a traced transaction.
> Handle max parameter size

- src/pg_tracing.h
- src/pg_tracing_active_spans.c
- src/pg_tracing_query_process.c
We can rely on span_context containing max_parameter_size plus we don't need the parameters_buffer to be passed as argument anymore.
> Simplify parameter extraction in normalise query

- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_planstate.c
Preallocate spans before running ExecutorRun to avoid span allocations inside error handler.
> Preallocate spans before ExecutorRun

- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_active_spans.c
- src/pg_tracing_planstate.c
- src/pg_tracing_span.c
- Remove unused functions
- Use planstate_walker to handle ExecProcNode overrides
- Always provide a valid timestamp to end_nested_level
> Cleaning and refactoring

- src/pg_tracing_planstate.c
Using lcons will possibly create new allocations which is something we want to avoid when disabling deparsing. Check that deparsing is enabled before maintaining the ancestor's list.
> Don't maintain ancestors' list if deparsing is disabled

- expected/parallel.out
- expected/setup.out
- sql/parallel.sql
- sql/setup.sql
- src/pg_tracing_planstate.c
Parallel queries executed without the leader participation won't execute the sub nodes in Gather/GatherMerge, which is represented by `need_to_scan_locally=false`. Since the nodes won't be executed, we won't have a traced plan and there's no value to generate spans from those nodes. 
We just need to skip the whole subtree in those cases.
Fixes #54
> Don't walk into Gather subplans if there's no local scan

- expected/parallel.out
- sql/parallel.sql
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_planstate.c
Currently, workers are created as children of ExecutorRun, leaving the Gather/GatherMerge node isolated and without any relation with the rest of the parallel queries.
This patch moves the Gather/GatherMerge node to be a parent of the worker's nodes.
> Set gather/gathermerge as parent of parallel workers

- src/pg_tracing.c
As max_trace_spans is used only for ASSERT, declare it with PG_USED_FOR_ASSERTS_ONLY.
> Avoid compiler warnings about unused variable

- .dir-locals.el
- .editorconfig
This makes the formatting right in editors, and in github diff view. The files are copied verbatim from PostgreSQL; we want the same formatting.
> Add .editorconfig and .dir-locals.el

- README.md
- src/pg_tracing.c
- src/pg_tracing.h
- src/pg_tracing_otel.c
Also the naptime and connection timeout settings. If no endpoint was set at server start, though, the background worker is not started, and changing the endpoint will have no effect. Similarly, if you set endpoint to empty while the server is running, the background worker will keep running, but won't do anything. Changing the registration of the background worker in response to config changes is difficult. But at least you can change the endpoint without a restart.
> Allow changing otel endpoint setting without restart

- t/003_change_endpoint.pl
Add tap test to check that modifying otel endpoint while server is running works and send the traces to the latest configured endpoint.
> Check otel endpoint update in tap test

- expected/utility.out
- sql/utility.sql
On HEAD, dc68515968 will capture SET's parameters as constants, allowing to normalise them and add placeholder. Update utility tests' expectation to avoid tracing SET queries.
> Update utility test expectation

- .github/workflows/publish-pg_tracing-pgxn.yml
- .github/workflows/run-tests.yml
- Dockerfile
- Makefile
- Makefile.dist
- common.mk
- packages/Makefile
- packages/deb.Dockerfile
Add workflow, dockerfile and makefile to create deb packages on release.
> CI deb release
